In [1]:
import pandas as pd

In [2]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(5,4)
matrix_data

array([[ 1.32835084, -0.27862769,  0.3586248 ,  0.06377406],
       [ 0.10121165,  1.6908594 , -1.48198962,  0.70795237],
       [ 0.72958467, -0.10890892,  0.37741126, -0.61344967],
       [-0.11579405,  0.52546966, -0.15203663, -0.32592362],
       [-0.52776936,  1.80420679,  0.19985456,  1.54299204]])

In [3]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(2,2)
matrix_data

array([[-0.20922873, -1.67038624],
       [-0.05471053, -0.40526099]])

In [4]:
# for same dtaa at every b run point 
import numpy as np
from numpy.random import randn as rn
np.random.seed(101)
matrix_data = rn(5,4)
matrix_data

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

### how to covert 2d array into Dataframe 

In [5]:
df = pd.DataFrame(matrix_data)
df

0         1         2         3
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [6]:
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
print("\nThe data frame looks like\n",'-'*45, sep='')
df


The data frame looks like
---------------------------------------------


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [7]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
#print("\nThe data frame looks like\n",'-'*45, sep='')
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

### Extracting data 

In [8]:
df['X']

A    1.693723
B    0.390528
C    0.072960
D   -0.754070
E    1.901755
Name: X, dtype: float64

In [9]:
df[['X','Y']]

X         Y
A  1.693723 -1.706086
B  0.390528  0.166905
C  0.072960  0.638787
D -0.754070 -0.943406
E  1.901755  0.238127

In [10]:
# row extracting 
df.loc['B']   #location of row index(name index)

W   -0.134841
X    0.390528
Y    0.166905
Z    0.184502
Name: B, dtype: float64

In [11]:
df.loc['D']

W   -0.497104
X   -0.754070
Y   -0.943406
Z    0.484752
Name: D, dtype: float64

In [12]:
type(df.loc['B'])

pandas.core.series.Series

### i want to extract data by default indexes 

In [13]:
df.iloc[0] #default indexs

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [14]:
df.iloc[2]

W    0.807706
X    0.072960
Y    0.638787
Z    0.329646
Name: C, dtype: float64

In [15]:
df.iloc[23] #out of index parameter 

IndexError: single positional indexer is out-of-bounds

In [17]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(5,4)
row_labels = [12,23,34,56,56,]
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
#print("\nThe data frame looks like\n",'-'*45, sep='')
df

W         X         Y         Z
12  0.386030  2.084019 -0.376519  0.230336
23  0.681209  1.035125 -0.031160  1.939932
34 -1.005187 -0.741790  0.187125 -0.732845
56 -1.382920  1.482495  0.961458 -2.141212
56  0.992573  1.192241 -1.046780  1.292765

In [18]:
df.loc[56]

W         X         Y         Z
56 -1.382920  1.482495  0.961458 -2.141212
56  0.992573  1.192241 -1.046780  1.292765

In [19]:
df.iloc[1]

W    0.681209
X    1.035125
Y   -0.031160
Z    1.939932
Name: 23, dtype: float64

### extraction of differ differ data from dataset(multiple row ) 

In [20]:
df.loc[[56,34]]

W         X         Y         Z
56 -1.382920  1.482495  0.961458 -2.141212
56  0.992573  1.192241 -1.046780  1.292765
34 -1.005187 -0.741790  0.187125 -0.732845

In [21]:
df.iloc[[4,1,2]]

W         X         Y         Z
56  0.992573  1.192241 -1.046780  1.292765
23  0.681209  1.035125 -0.031160  1.939932
34 -1.005187 -0.741790  0.187125 -0.732845

In [22]:
df.iloc[[4,1,2],[1]]  #row, col

X
56  1.192241
23  1.035125
34 -0.741790

In [23]:
df.iloc[[1,2],[1,2]]

X         Y
23  1.035125 -0.031160
34 -0.741790  0.187125

In [24]:
df.loc[[23,34],['X','Y']]

X         Y
23  1.035125 -0.031160
34 -0.741790  0.187125

In [25]:
df.iloc[[0,-1],[0,-1]]

W         Z
12  0.386030  0.230336
56  0.992573  1.292765

In [26]:
df.iloc[[0,4],[0,3]]

W         Z
12  0.386030  0.230336
56  0.992573  1.292765

In [27]:
df.loc[23:56,'W':'Z']

W         X         Y         Z
23  0.681209  1.035125 -0.031160  1.939932
34 -1.005187 -0.741790  0.187125 -0.732845
56 -1.382920  1.482495  0.961458 -2.141212
56  0.992573  1.192241 -1.046780  1.292765

In [31]:
print('create a new columna ')
df['New_COl'] = df['X'] + df['Y']
df
df['New_COl(sum X and Y )'] = df['X'] + df['Y']
df

create a new columna 


W         X         Y         Z   New_COl  New_COl(sum X and Y )
12  0.386030  2.084019 -0.376519  0.230336  1.707500               1.707500
23  0.681209  1.035125 -0.031160  1.939932  1.003965               1.003965
34 -1.005187 -0.741790  0.187125 -0.732845 -0.554665              -0.554665
56 -1.382920  1.482495  0.961458 -2.141212  2.443954               2.443954
56  0.992573  1.192241 -1.046780  1.292765  0.145461               0.145461

### droping col and row in pandas 

In [32]:
df.drop('X', axis=1)  #axis = 0/1 means row and col erspectivily 

W         Y         Z   New_COl  New_COl(sum X and Y )
12  0.386030 -0.376519  0.230336  1.707500               1.707500
23  0.681209 -0.031160  1.939932  1.003965               1.003965
34 -1.005187  0.187125 -0.732845 -0.554665              -0.554665
56 -1.382920  0.961458 -2.141212  2.443954               2.443954
56  0.992573 -1.046780  1.292765  0.145461               0.145461

In [33]:
df  #gere X col is present there so delet permannenetly 

W         X         Y         Z   New_COl  New_COl(sum X and Y )
12  0.386030  2.084019 -0.376519  0.230336  1.707500               1.707500
23  0.681209  1.035125 -0.031160  1.939932  1.003965               1.003965
34 -1.005187 -0.741790  0.187125 -0.732845 -0.554665              -0.554665
56 -1.382920  1.482495  0.961458 -2.141212  2.443954               2.443954
56  0.992573  1.192241 -1.046780  1.292765  0.145461               0.145461

In [34]:
df.drop('X', axis=1, inplace=True)

In [35]:
df  #now X col deleted just bcs of inplace = True

W         Y         Z   New_COl  New_COl(sum X and Y )
12  0.386030 -0.376519  0.230336  1.707500               1.707500
23  0.681209 -0.031160  1.939932  1.003965               1.003965
34 -1.005187  0.187125 -0.732845 -0.554665              -0.554665
56 -1.382920  0.961458 -2.141212  2.443954               2.443954
56  0.992573 -1.046780  1.292765  0.145461               0.145461

# About Row

In [36]:
df.drop(34)

W         Y         Z   New_COl  New_COl(sum X and Y )
12  0.386030 -0.376519  0.230336  1.707500               1.707500
23  0.681209 -0.031160  1.939932  1.003965               1.003965
56 -1.382920  0.961458 -2.141212  2.443954               2.443954
56  0.992573 -1.046780  1.292765  0.145461               0.145461

In [37]:
df

W         Y         Z   New_COl  New_COl(sum X and Y )
12  0.386030 -0.376519  0.230336  1.707500               1.707500
23  0.681209 -0.031160  1.939932  1.003965               1.003965
34 -1.005187  0.187125 -0.732845 -0.554665              -0.554665
56 -1.382920  0.961458 -2.141212  2.443954               2.443954
56  0.992573 -1.046780  1.292765  0.145461               0.145461

In [38]:
df.drop(56, inplace=True)

In [39]:
df

W         Y         Z   New_COl  New_COl(sum X and Y )
12  0.386030 -0.376519  0.230336  1.707500               1.707500
23  0.681209 -0.031160  1.939932  1.003965               1.003965
34 -1.005187  0.187125 -0.732845 -0.554665              -0.554665

In [40]:
# default indexing not goign to understand omly name indexin not goign to work 
df.drop[0]

TypeError: 'method' object is not subscriptable

# IX operation 

in future it will not the part of panda s

In [46]:
df.ix[23,'W']

c:\users\lenovo\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


0.6812092925867574

In [47]:
df.ix[0:2, 1:3]

c:\users\lenovo\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
c:\users\lenovo\appdata\local\programs\python\python36\lib\site-packages\pandas\core\indexing.py:822: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)


Empty DataFrame
Columns: [Y, Z]
Index: []

# Conditoin filtring condition 

In [50]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
#print("\nThe data frame looks like\n",'-'*45, sep='')
df

W         X         Y         Z
A  1.606780 -1.115710 -1.385379 -1.329660
B  0.041460 -0.411055 -0.771329  0.110477
C -0.804652  0.253548  0.649148  0.358941
D -1.080471  0.902398  0.161781  0.833029
E  0.975720 -0.388239  0.783316 -0.708954

In [51]:
print(df>0)

       W      X      Y      Z
A   True  False  False  False
B   True  False  False   True
C  False   True   True   True
D  False   True   True   True
E   True  False   True  False


In [52]:
print('/n')
df.loc[['A','B','C']]>0

/n


W      X      Y      Z
A   True  False  False  False
B   True  False  False   True
C  False   True   True   True

In [53]:
df[df.loc[['A','B','C']]>0]  #if we fill it into data frame 

W         X         Y         Z
A  1.60678       NaN       NaN       NaN
B  0.04146       NaN       NaN  0.110477
C      NaN  0.253548  0.649148  0.358941
D      NaN       NaN       NaN       NaN
E      NaN       NaN       NaN       NaN

In [54]:

import pandas as pd 
import numpy as np
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [56]:
df = pd.DataFrame(data = matrix_data, index=row_labels, columns=column_headings)
print('\nA new Dataframe \n')
df


A new Dataframe 



Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [59]:
df['Height']

A    66
B    70
C    62
D    68
E    62
Name: Height, dtype: int32

In [60]:
df['Height']<65

A    False
B    False
C     True
D    False
E     True
Name: Height, dtype: bool

In [61]:
df[df['Height']<65]

Age  Height  Weight
C   30      62     125
E   25      62     152

In [58]:
df[df['Height']>65]

Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [71]:
df[(df['Height']>65) & (df['Weight']>125) & (df['Age']>30)]

Age  Height  Weight
B   42      70     148
D   35      68     160

In [72]:
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']


In [74]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe DataFrame\n",'-'*25, sep='')
df



The DataFrame
-------------------------


Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [75]:
# i want default index 
df.reset_index()  #but still e have old indexes here 

index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152

In [76]:
df.reset_index(drop=True)  #now uts workibg properly 

Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152

In [77]:
df  #but still its not changes in df 

Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [78]:
df.reset_index(drop=True, inplace=True)

In [79]:
df

Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152

# how to set the indexes 

In [80]:
"student Teacher Engineer Doctor Nurse".split()

['student', 'Teacher', 'Engineer', 'Doctor', 'Nurse']

In [81]:
df['xyz']="student Teacher Engineer Doctor Nurse".split()
df['xyz']

0     student
1     Teacher
2    Engineer
3      Doctor
4       Nurse
Name: xyz, dtype: object

In [82]:
df

Age  Height  Weight       xyz
0   22      66     140   student
1   42      70     148   Teacher
2   30      62     125  Engineer
3   35      68     160    Doctor
4   25      62     152     Nurse

In [83]:
df.set_index('xyz')

Age  Height  Weight
xyz                          
student    22      66     140
Teacher    42      70     148
Engineer   30      62     125
Doctor     35      68     160
Nurse      25      62     152

In [84]:
#multi-indexing
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
#two lwvwl of heririchy 

In [89]:
list(zip(outside,inside))  #zip based of the indexes ehere we have pair of data  

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [85]:
print("\nTuple pairs after the zip and list command\n",'-'*45, sep='')
print(hier_index)



Tuple pairs after the zip and list command
---------------------------------------------
[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]


In [86]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
print("\nIndex hierarchy\n",'-'*25, sep='')
print(hier_index)




Index hierarchy
-------------------------
MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )


In [87]:
print("\nIndex hierarchy type\n",'-'*25, sep='')
print(type(hier_index))


Index hierarchy type
-------------------------
<class 'pandas.core.indexes.multi.MultiIndex'>


In [88]:
print("\nCreating DataFrame with multi-index\n",'-'*37, sep='')
#np.random.seed(101)
df1 = pd.DataFrame(data=np.round(rn(6,3)), index= hier_index, columns= ['A','B','C'])
print(df1)


Creating DataFrame with multi-index
-------------------------------------
        A    B    C
G1 1  1.0 -2.0  1.0
   2  0.0 -2.0  0.0
   3 -1.0  2.0  0.0
G2 1  2.0  1.0 -1.0
   2  0.0  0.0  1.0
   3 -2.0 -0.0 -1.0


In [90]:
df1.loc['G1']

A    B    C
1  1.0 -2.0  1.0
2  0.0 -2.0  0.0
3 -1.0  2.0  0.0

In [94]:
df1.loc['G1'].loc[3,['B','C']]

B    2.0
C    0.0
Name: 3, dtype: float64

In [96]:
df1.ix['G1'].iloc[2,[1,2]]

c:\users\lenovo\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


B    2.0
C    0.0
Name: 3, dtype: float64

In [99]:
l1 = ['A','A','A','B','B','B','C','C','C']
l2 = [1,2,3,1,2,3,1,2,3]
l3 = [1,2,3,4,5,6,7,8,9]
l = list(zip(l1,l2,l3))
g =  pd.MultiIndex.from_tuples(l)
df = pd.DataFrame(data = np.round(rn(9,4)), index = g)
df

0    1    2    3
A 1 1  0.0  0.0  0.0  1.0
  2 2 -0.0  1.0 -0.0 -0.0
  3 3  0.0  0.0 -1.0  2.0
B 1 4 -1.0 -2.0  1.0  1.0
  2 5  0.0 -1.0 -1.0 -0.0
  3 6 -0.0  0.0  0.0  1.0
C 1 7 -1.0 -2.0 -0.0 -2.0
  2 8 -3.0  2.0  0.0 -1.0
  3 9 -0.0  2.0  1.0  1.0

In [100]:
df = pd.DataFrame({'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]})
df['States']="CA NV AZ".split()
df.set_index('States',inplace=True)
print(df)

          A    B  C
States             
CA      1.0  5.0  1
NV      2.0  NaN  2
AZ      NaN  NaN  3


In [101]:
df

A    B  C
States             
CA      1.0  5.0  1
NV      2.0  NaN  2
AZ      NaN  NaN  3

In [102]:
df.dropna(axis=1)

C
States   
CA      1
NV      2
AZ      3

In [103]:
df.dropna()

A    B  C
States             
CA      1.0  5.0  1

### if nan value have some condition , by setting threshold parameter 

In [106]:
# Require that many non-Na valau 
df.dropna(thresh=2)

A    B  C
States             
CA      1.0  5.0  1
NV      2.0  NaN  2

In [107]:
# Require that many non-Na valau , look for atleas one non-Na value 
df.dropna(thresh=1)

A    B  C
States             
CA      1.0  5.0  1
NV      2.0  NaN  2
AZ      NaN  NaN  3

In [108]:
# Require that many non-Na valau , look for atleas three non-Na value 
df.dropna(thresh=3)

A    B  C
States             
CA      1.0  5.0  1

In [109]:
# Require that many non-Na valau , look for atleas four  non-Na value 
df.dropna(thresh=4)

Empty DataFrame
Columns: [A, B, C]
Index: []

In [110]:
df.dropna(thresh=3, axis=1)

C
States   
CA      1
NV      2
AZ      3

In [111]:
df

A    B  C
States             
CA      1.0  5.0  1
NV      2.0  NaN  2
AZ      NaN  NaN  3